[package]
name = "csim"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.32"
ordered-float = { version = "5.0.0", features = ["libm", "serde"] }
rand = "0.9.0"
serde = {version= "1.0.219", features = ["derive"]}
toml = "0.8.20"
