[package]
name = "csim"
version = "0.1.0"
edition = "2021"

[dependencies]
ordered-float = { version = "5.0.0", features = ["libm", "serde"] }
serde = {version= "1.0.219", features = ["derive"]}
toml = "0.8.20"
