items = [
{label = "A0", cost = 2, size = 3},
{label = "B0", cost = 3, size = 4},
{label = "C0", cost = 4, size = 9},
{label = "D0", cost = 1, size = 8},
]
 
trace = [
"A0",
"B0",
"C0",
"D0",
"B0",
"D0",
] 
